### PR TITLE
Export more utils and EmailPasswordForm

### PR DESCRIPTION
**Pull request by NikolaiMadlener**
# Export more utils and EmailPasswordForm

## :recycle: Current situation & Problem
In the Spezi-Web-Health-Components it would be neat if we could make use of `useOpenState`. In the Spezi-Web-Template-App the same applies for the `EmailPasswordForm`.

## :gear: Release Notes 
- export `useOpenState`, `misc`, and `EmailPasswordForm` in the `index.ts`.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by arkadiuszbachorski — APPROVED** [review]
We shouldn't use direct imports in example applications or packages. Whenever `@stanfordspezi/spezi-web-design-system` is imported as a whole, `index.js` is requested. `index.js` contains all the dependencies of every design system file. Of course, some builders will tree-shake whatever is used, but it's not always as effective. For example, if application uses just buttons and navigation, they don't need to import `DataTable` and `Form` dependencies.

Better way to consume the design system is by selecting specific modules path, see how ENGAGE does it. 

Anyways, this is completely fine to land. I still want to keep `index.js` root import. Sometimes, people don't care about bundle size and/or it's easier for them to just consume it all from root.

**Comment by NikolaiMadlener** [comment]
> We shouldn't use direct imports in example applications or packages. Whenever `@stanfordspezi/spezi-web-design-system` is imported as a whole, `index.js` is requested. `index.js` contains all the dependencies of every design system file. Of course, some bundlers will tree-shake to remove unused code, but it's not always as effective. For example, if application uses just buttons and navigation, they don't need to import `DataTable` and `Form` dependencies.
> 
> Better way to consume the design system is by selecting specific modules path, see how ENGAGE does it.
> 
> Anyways, this is completely fine to land. I still want to keep `index.js` root import. Sometimes, people don't care about bundle size and/or it's easier for them to just consume it all from root.

Gotcha! 
However, I think with the current version of the design-system it's not possible to import e.g. `'@stanfordspezi/spezi-web-design-system/src/utils/'`.

**Comment by NikolaiMadlener** [comment]
@arkadiuszbachorski How do we deal the the codecov/patch check?

**Comment by arkadiuszbachorski** [comment]
@NikolaiMadlener I moved export of `EmailPasswordForm` from `index.ts` directly to `SignInForm/index.ts`. This enables `EmailPasswordForm` to be accessible both from global import and `SignInForm` direct import, without adding new path just for `EmailPasswordForm`. 

`EmailPasswordForm` is just part of `SignInForm`, it doesn't have to be used alone, as there there is `enableEmailPassword` prop of `SignInForm`, that glues them together. 

[Move EmailPasswordForm export to SignInForm module](https://github.com/StanfordSpezi/spezi-web-design-system/pull/11/commits/7b542b2325b956398f73fa95ec5ae1415522f038)

**Pull request merged**
